#!/bin/bash

# Define the Python script and input file
PYTHON_SCRIPT="solver_random_2-opt.py"
INPUT_FILE="input_5.csv"
NUM_ITERATIONS=100
OUTPUT_DIR="solver_outputs" # Directory to store all output files

# Create the output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Initialize variables to store the best result
LOWEST_DISTANCE=21305 # Initialize with a very high number
BEST_OUTPUT_FILE=""

echo "Running $PYTHON_SCRIPT $INPUT_FILE for $NUM_ITERATIONS iterations..."

for i in $(seq 1 $NUM_ITERATIONS); do
    echo "Iteration $i"
    
    # Run the Python script and capture its output
    # Redirect stdout to a temporary file for processing
    TEMP_OUTPUT_FILE="${OUTPUT_DIR}/temp_output_${i}.txt"
    python3 "$PYTHON_SCRIPT" "$INPUT_FILE" > "$TEMP_OUTPUT_FILE" 2>&1

    # Extract the total distance from the Python script's output
    # The script prints "shortest_tour total distance: <distance>"
    CURRENT_DISTANCE=$(grep "shortest_tour total distance:" "$TEMP_OUTPUT_FILE" | awk '{print $NF}')
    
    # Get the actual output CSV filename generated by the Python script
    # The script prints "tour saved to output_<challenge_number>.csv"
    GENERATED_CSV_FILE=$(grep "tour saved to" "$TEMP_OUTPUT_FILE" | awk '{print $NF}')

    # Compare with the lowest distance found so far
    if (( $(echo "$CURRENT_DISTANCE < $LOWEST_DISTANCE" | bc -l) )); then
        LOWEST_DISTANCE="$CURRENT_DISTANCE"
        BEST_OUTPUT_FILE="$GENERATED_CSV_FILE"
        echo "NEW LOWEST DISTANCE FOUND: $LOWEST_DISTANCE (from $BEST_OUTPUT_FILE)"
        
        # Rename the best output file to a more permanent name
        cp "$BEST_OUTPUT_FILE" "${OUTPUT_DIR}/best_output_${INPUT_FILE%.*}.csv"
    fi
    
    # Clean up the temporary output file
    rm "$TEMP_OUTPUT_FILE"

done

echo "--- Script finished ---"
echo "Lowest total distance found: $LOWEST_DISTANCE"
echo "Output saved to: ${OUTPUT_DIR}/best_output_${INPUT_FILE%.*}.csv"
echo "All intermediate CSV outputs are in the '$OUTPUT_DIR' directory."